@startuml
class Chart2DContentViewModel {
    + Title : string <<get>>
    + AxisXLabel : string <<get>>
    + AxisYLabel : string <<get>>
    + RenderData : ICollection<IRenderData> <<get>>
    + Chart2DContentViewModel(title:string, axisXLabel:string, axisYLabel:string, content:IEnumerable<IRenderData>)
    + Dispose() : void
}
IDisposable <|-- Chart2DContentViewModel
@enduml
