@startuml
class DynamicReconParamsNode {
    + {static} DisplayInfo : NodeDisplayInfo <<get>>
    + <<const>> UniqueId : string = "GPM.CustomAnalysis.DynamicRecon.DynamicReconParamsNode"
    - <<readonly>> dynamicReconParam : DynamicReconParams
    + Options : DynamicReconParamsOptions <<get>>
    + DynamicReconParamsNode(services:IAnalysisNodeBaseServices)
    + <<async>> Run() : Task<DynamicReconResults?>
    # <<override>> GetSaveContent() : byte[]?
    # <<override>> OnCreated(eventArgs:NodeCreatedEventArgs) : void
    - OptionsOnPropertyChanged(sender:object?, e:PropertyChangedEventArgs) : void
}
class NodeDisplayInfo {
    + Title : string <<get>> = "GPM Dynamic Recon Params"
    + Icon : ImageSource? <<get>> = null
}
AnalysisNodeBase <|-- DynamicReconParamsNode
DynamicReconParamsNode +-- NodeDisplayInfo
INodeDisplayInfo <|-- NodeDisplayInfo
@enduml
